In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/potential-talents - Aspiring human resources - seeking human resources.csv")

df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN

In [3]:
df = df.drop("fit",axis=1)

In [4]:
df.head()

,id,job_title,location,connection
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500+
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+

In [7]:
print(df["connection"].unique())

['85' '500+ ' '44' '1' '61' '2' '390' '57' '82' '5' '7' '16' '212' '409'
 '52' '455' '174' '268' '50' '4' '40' '18' '349' '155' '39' '64' '9' '415'
 '19' '71' '48' '103' '49']

In [8]:
df['connection'] = df['connection'].replace("500+ ","500")

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 0 to 103
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          52 non-null     int64
 1   job_title   52 non-null     object
 2   location    52 non-null     object
 3   connection  52 non-null     object
dtypes: int64(1), object(3)
memory usage: 2.0+ KB

In [18]:
df = df.drop_duplicates(subset=['job_title'])

In [22]:
df.head(60)

,id,job_title,location,connection
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44
3,4,People Development Coordinator at Ryan,"Denton, Texas",500
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1
6,7,Student at Humber College and Aspiring Human R...,Kanada,61
7,8,HR Senior Specialist,San Francisco Bay Area,500
9,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500
10,11,Student at Chapman University,"Lake Forest, California",2
11,12,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500
12,13,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500
26,27,Aspiring Human Resources Management student se...,"Houston, Texas Area",500
27,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390
65,66,Experienced Retail Manager and aspiring Human ...,"Austin, Texas Area",57
66,67,"Human Resources, Staffing and Recruiting Profe...","Jackson, Mississippi Area",500
67,68,Human Resources Specialist at Luxottica,Greater New York City Area,500
68,69,"Director of Human Resources North America, Gro...","Greater Grand Rapids, Michigan Area",500
69,70,"Retired Army National Guard Recruiter, office ...","Virginia Beach, Virginia",82
70,71,"Human Resources Generalist at ScottMadden, Inc.","Raleigh-Durham, North Carolina Area",500
71,72,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5
72,73,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7
73,74,Human Resources Professional,Greater Boston Area,16
74,75,"Nortia Staffing is seeking Human Resources, Pa...","San Jose, California",500
75,76,Aspiring Human Resources Professional | Passio...,"New York, New York",212
76,77,Human Resources|\nConflict Management|\nPolici...,Dallas/Fort Worth Area,409
77,78,Human Resources Generalist at Schwan's,Amerika Birleşik Devletleri,500
78,79,Liberal Arts Major. Aspiring Human Resources A...,"Baton Rouge, Louisiana Area",7
79,80,Junior MES Engineer| Information Systems,"Myrtle Beach, South Carolina Area",52
80,81,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455
81,82,Aspiring Human Resources Professional | An ene...,"Austin, Texas Area",174
82,83,HR Manager at Endemol Shine North America,"Los Angeles, California",268
83,84,Human Resources professional for the world lea...,"Highland, California",50
84,85,RRP Brand Portfolio Executive at JTI (Japan To...,Greater Philadelphia Area,500
85,86,Information Systems Specialist and Programmer ...,"Gaithersburg, Maryland",4
86,87,Bachelor of Science in Biology from Victoria U...,"Baltimore, Maryland",40
87,88,Human Resources Management Major,"Milpitas, California",18
88,89,Director Human Resources at EY,Greater Atlanta Area,349
89,90,Undergraduate Research Assistant at Styczynski...,Greater Atlanta Area,155
90,91,Lead Official at Western Illinois University,Greater Chicago Area,39
91,92,Seeking employment opportunities within Custom...,"Torrance, California",64
92,93,Admissions Representative at Community medical...,"Long Beach, California",9
93,94,Seeking Human Resources Opportunities. Open t...,Amerika Birleşik Devletleri,415
94,95,Student at Westfield State University,"Bridgewater, Massachusetts",57
95,96,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19
97,98,Student,"Houston, Texas Area",4
98,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48
99,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49
102,103,Always set them up for Success,Greater Los Angeles Area,500
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500